version: "3.9"

services:
  mongo:
    image: mongo:latest
    container_name: medicine_mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: medicine_db
    volumes:
      - mongo_data:/data/db
    networks:
      - mms-network

  backend:
    build: ./backend
    container_name: medicine_backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev
    networks:
      - mms-network

  frontend:
    build: ./frontend
    container_name: medicine_frontend
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev
    networks:
      - mms-network

volumes:
  mongo_data:

networks:
  mms-network:
    driver: bridge
